apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hasher-netpol
spec:
  ingress:
    -
      from:
        -
          podSelector:
            matchLabels:
              app: worker
      ports:
        -
          port: 8080
          protocol: TCP
  podSelector:
    matchLabels:
      app: hasher
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-netpol
spec:
  ingress:
    -
      from:
        -
          podSelector:
            matchLabels:
              app: webui
        -
          podSelector:
            matchLabels:
              app: worker
      ports:
        -
          port: 6379
          protocol: TCP
  podSelector:
    matchLabels:
      app: redis
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rng-netpol
spec:
  ingress:
    -
      from:
        -
          podSelector:
            matchLabels:
              app: worker
      ports:
        -
          port: 8080
          protocol: TCP
  podSelector:
    matchLabels:
      app: rng
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: webui-netpol
spec:
  ingress:
    -
      ports:
        -
          port: 8080
          protocol: TCP
  podSelector:
    matchLabels:
      app: webui
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: worker-netpol
spec:
  podSelector:
    matchLabels:
      app: worker
  policyTypes:
    - Ingress
---
apiVersion: v1
kind: Service
metadata:
  name: hasher
spec:
  ports:
    -
      port: 8080
      protocol: TCP
      targetPort: 8080      
  selector:
    app: hasher
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    -
      port: 6379
      protocol: TCP
      targetPort: 6379      
  selector:
    app: redis
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: rng
spec:
  ports:
    -
      port: 8080
      protocol: TCP
      targetPort: 8080      
  selector:
    app: rng
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: webui-svc
spec:
  ports:
    -
      nodePort: 30080
      port: 8080
      protocol: TCP
      targetPort: 8080      
  selector:
    app: webui
  type: NodePort
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hasher-rs
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: hasher
  template:
    metadata:
      labels:
        app:hasher
    spec:
      containers:
      initContainers:
      volumes:
---
