apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rng
spec:
  selector:
    matchLabels:
      app: rng
  template:
    metadata:
      labels:
        app: hasher
    spec:
      containers:
        - image: localhost/hasher
          name: hasher
          ports:
            - containerPort: 8080
